src/ProfilePage/urls.py
from django.urls import path


from . import views

urlpatterns = [
    path('', views.index),
    path('<int:tweet_id>/', views.tweetInfo),
    path('edit/', views.edit),
    path('update/', views.update),
    path('ownsAccount/', views.ownsAccount, name='ownsAccount')
]

src/Twooter/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('home/', include('HomePage.urls')),
    path('login/', include('LoginPage.urls')),
    path('register/', include('RegisterPage.urls')),
    path('admin/', admin.site.urls),
    path('', views.index),
    path('<str:account_name>/', include('ProfilePage.urls'))
    #path(r'^.*$', views.index),
    # re_path(r'', views.index)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/ProfilePage/models.py
from django.db import models
from HomePage.models import BasicUserDB

# Create your models here.
class UserProfile(models.Model):
    user = models.ForeignKey(BasicUserDB, 
    on_delete=models.CASCADE)

    date_created = models.DateTimeField(auto_now_add=True,
    null=False)

    profile_pic = models.ImageField(upload_to='profile_pics/')

    bio = models.TextField()

src/ProfilePage/forms.py
from django import forms

class EditProfile(forms.Form):
    profile_pic = forms.ImageField(required=False)
    bio = forms.CharField(max_length=300, required=False)

src/ProfilePage/views.py
from datetime import datetime
import os
from django.http import JsonResponse
from django.shortcuts import HttpResponse, redirect, render
from django.core.exceptions import ObjectDoesNotExist
from HomePage.models import TweetDB
from HomePage.models import BasicUserDB
from ProfilePage.forms import EditProfile

from Twooter.session_authentication import SA

from .models import UserProfile

# Create your views here.
def index(request, account_name):
    response = HttpResponse()
    response = SA.validate(request, response)
    if SA.validateForLogin(request):
        try:
            user = UserProfile.objects.get(user__username=account_name)
            tweets_list = TweetDB.objects.filter(user__username=account_name)
            tweets = {}
            for twt in tweets_list:
                created_on = datetime.now().timestamp() - twt.created_on
                # If greater than 60 seconds
                if created_on >= 60:
                    created_on /= 60
                    # If greater than 60 minutes
                    if created_on >= 60:
                        created_on /= 60
                        # If greater than 24 hours
                        if created_on >= 24:
                            created_on /= 24
                            # If greater than 30 days
                            if created_on >= 30:
                                created_on /= 30
                                # If greater than 12 months
                                if created_on >= 12:
                                    created_on /= 12
                                    created_on = str(int(created_on)) + 'year'
                                else:
                                    created_on = str(int(created_on)) + 'months'
                            else:
                                created_on = str(int(created_on)) + 'days'
                        else:
                            created_on = str(int(created_on)) + 'hr'
                    else:
                        created_on = str(int(created_on)) + 'm'
                else:
                    created_on = str(int(created_on)) + 's'
                tweets[int(twt.tweetID)] = {'tweet': twt, 'created_on' : created_on}
            logUser = UserProfile.objects.filter(user__userID=request.COOKIES["userID"])[0]
            response = render(request,'ProfilePage/profile.html', {'logUser':logUser,'user':user, 'tweets':tweets})
        except ObjectDoesNotExist:
            response = HttpResponse("Account like that does not exist")
    return response

def tweetInfo(request, account_name, tweet_id):
    response = HttpResponse()
    response = SA.validate(request, response)
    if SA.validateForLogin(request):
        try:
            tweet = TweetDB.objects.get(user__username=account_name, tweetID=tweet_id)
            profile_pic = UserProfile.objects.filter(user=tweet.user)[0].profile_pic
            user = UserProfile.objects.filter(user__userID=request.COOKIES["userID"])[0]
            response = render(request, 'ProfilePage/tweet.html', {'tweet':tweet, 'created_on':datetime.fromtimestamp(tweet.created_on),'profile_pic':profile_pic, 'user':user})
        except ObjectDoesNotExist:
            response = HttpResponse("Page like was not found")
    return response

def edit(request, account_name):
    response = HttpResponse()
    response = SA.validate(request, response)
    if SA.validateForLogin(request):
        user = BasicUserDB.objects.filter(username=account_name, userID=request.COOKIES['userID'])
        if len(user) > 0:
            user = UserProfile.objects.filter(user=user[0])
            if len(user) > 0:
                response = render(request, 'ProfilePage/profileEdit.html', {'user': user[0]})
            else: 
                response = redirect('/login/')
        else:
            user = BasicUserDB.objects.filter(userID=request.COOKIES['userID'])
            if len(user) > 0:
                response = redirect('/' + user[0].username + '/edit')
            else:
                response = redirect('/login/')
    return response

def update(request, account_name):
    response = HttpResponse()
    response = SA.validate(request, response)
    if SA.validateForLogin(request):
        if request.method == 'POST':
            print(request.POST)
            print(type(request.FILES.get('profile_pic')))
            new_profile = UserProfile.objects.filter(user=BasicUserDB.objects.filter(userID=request.COOKIES['userID'])[0])[0]
            old_profile_pic = ''
            if request.POST.get('bio') != "":
                new_profile.bio = request.POST.get('bio')
            if request.FILES.get('profile_pic') != None:
                file = request.FILES.get('profile_pic')
                old_profile_pic = new_profile.profile_pic
                file.name = str(int(new_profile.user.userID)) + file.name[file.name.index('.'):]
                new_profile.profile_pic = file
            new_profile.save()
            # if old_profile_pic != "":
            #     deleteOldPic(old_profile_pic,new_profile.profile_pic)
            response = redirect('/' + account_name + "/")
        else:
            response = redirect('/' + account_name + "/")
    return response

def ownsAccount(request, account_name):
    if SA.validateForLogin(request):
        user = BasicUserDB.objects.filter(username=account_name, userID=request.COOKIES['userID'])
        if len(user) > 0:
            return JsonResponse({'ownsAccount': True})
        else:
            return JsonResponse({'ownsAccount': False})
    else:
        return JsonResponse({'logOutLMAO': True})

def deleteOldPic(oldFile, newFile):
    try:
        os.remove(str(oldFile.file))
        os.rename(str(newFile.file), str(oldFile.file))
    except FileNotFoundError:
        pass
    except FileExistsError:
        pass

src/templates/ProfilePage/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'ProfilePage/css/profile_style.css' %}">
    <title>{{user.user.username}}</title>
</head>
<body>

    <!-- <h1>{{user.user.username}} #{{user.user.userTag}}</h1>
    <h3 style="display: inline;">Created on: </h3>
    <p style="display: inline; color: rgb(154, 154, 154);">{{user.date_created}}</p><br><br>
    {% if user.profile_pic %}
    <img src="/media/{{user.profile_pic}}" alt="Profile Pic"><br><br>
    {% else %}
    <img src="{% static 'ProfilePage/unknown.jpg' %}" alt="Profile Pic Not Set"><br><br>
    {% endif %}
    <h3 style="display: inline;">Bio: </h3>
    <p style="display: inline;">{{user.bio}}</p><br><br>
    <button id="edit-profile" onclick="window.location.href= '/{{user.user.username}}/edit' " hidden>Edit Profile</button>
    <h3>Tweets: </h3>
    <div id="tweets-box">
        {% for twt, value in tweets.items %}
            <div class="tweet" id="{{twt}}" onclick="window.location.href = '/{{value.tweet.user.username}}/{{twt}}'">
                <a href="/{{value.tweet.user.username}}">
                    <p class="author">{{value.tweet.user.username}}</p>
                    <p style="display: inline; color: gray;">{{value.created_on}}</p>
                </a>
                <br>
                <p class="message">{{value.tweet.message}}</p>
            </div>
        {% endfor %}
    </div> -->

    <div class="container">
        <div class="header_container">
            <div id="logo_container">
                <img src="{% static 'LoginPage/img/twitter_small_logo.png'%}" alt="" onclick="window.location.href = '/home/'">
                <a href="/home/"><p>Twooter</p></a>
            </div>
            <div id="profile_tab">
                <a href="/{{logUser.user.username}}" id="profile_tab_button">
                    <p>{{  logUser.user.username }}</p> 
                    <img src="/media/{{logUser.profile_pic}}" alt="Profile Pic">
                </a>
            </div>
        </div>
        <div id="main_container">
            <div id="nav_container">
                <div id="nav_buttons">
                    <a href="/home/" class="nav_button">
                        <span class="material-symbols-outlined">
                            home
                        </span>
                        <p>Feed</p>
                    </a>
                    <a href="/{{user.username}}/" class="nav_button">
                        <span class="material-symbols-outlined">
                            person
                        </span>
                        <p>Profile</p>
                    </a>
                </div>
                <div id="logOut_container">
                    <button onclick="logOut()">Log Out</button>
                </div>
            </div>
            <div id="tweets-container">
                <div id="user_profile">
                    <div id="banner"></div>
                    <div id="profile_data">
                        <div id="profile_data_imgBtn">
                            <img src="/media/{{user.profile_pic}}" alt="Profile Pic">
                            <div id="profile_data_btn">
                                <button id="edit_profile" onclick="window.location.href= '/{{user.user.username}}/edit'" hidden>Edit Profile</button>
                            </div>
                        </div>
                        <p id="username">{{user.user.username}}</p>
                        <p id="bio">{{user.bio}}</p>
                    </div>
                </div>
                <div id="tweets_box">
                    {% for twt, value in tweets.items %}
                        <div class="tweet" id="{{twt}}" onclick="window.location.href = '/{{value.tweet.user.username}}/{{twt}}'">
                            <a href="/{{value.tweet.user.username}}">
                                <img src="/media/{{user.profile_pic}}" alt="Profile Pic">
                                <p class="author">{{value.tweet.user.username}}</p>
                                <p style="display: inline; color: gray;">{{value.created_on}}</p>
                            </a>
                            <br>
                            <p class="message">{{value.tweet.message}}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div id="activity_container"></div>
        </div>
    </div>
    
    <script>

        $(window).on('load', () => {
            $.ajax({
                type:'GET',
                url:"{% url 'ownsAccount' 'account_name' %}".replace('account_name', '{{user.user.username}}'),
                success: function(response) {
                    if(response.logOutLMAO)
                        return window.location.reload()
                    if(response.ownsAccount)
                        $('#edit_profile').show()
                },
                error: function() {
                    alert("An Error has Occured")
                }
            })
        })

    </script>

</body>
</html>

src/templates/ProfilePage/profileEdit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'ProfilePage/css/profileEdit_style.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    <title>Edit Profile</title>
    <style>
        img {
            height: 300px;
        }
        #photoInput:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <div class="container">
        <div id="edit_container">
            <form action="/{{user.user.username}}/update/" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div id="save_container">
                    <span class="material-symbols-outlined" onclick="window.location.href = '/{{user.user.username}}'">
                        close
                    </span>
                    <p>Edit Profile</p>
                    <div id="save_btn">
                        <input type="submit" value="Save">
                    </div>
                </div>
                <div id="main_content">
                    <div for="id_profile_pic" id="image_container" style="background-image: url('/media/{{user.profile_pic}}');">
                        <div id="change_div">
                            <span class="material-symbols-outlined">
                                change_circle
                            </span>
                        </div>
                    </div>
                    <!-- <img src="/media/{{user.profile_pic}}" alt="Profile Pic"> -->
                    <input type="file" name="profile_pic" id="id_profile_pic" accept="image/png, image/gif, image/jpeg, image/jpg" onchange="changeBackgroundImage(this)" hidden>
                    <p hidden>Image has been loaded</p>
                    <div class="input_box unselect">
                        <div class="label">Name</div>
                        <p id="username">{{user.user.username}}</p>
                    </div>
                    <div class="input_box">
                        <div class="label">Bio</div>
                        <input type="text" name="bio" id="id_bio" value="{{user.bio}}">
                    </div>
                </div>
            </form>
        </div>
    </div>
    <script>
        $('.input_box input').focus(e => {
            e.target.parentElement.style.border = '1px solid rgb(72, 72, 198)'
            e.target.parentNode.firstElementChild.style.color = 'rgb(72, 72, 198)'
        }).blur(e => {
            e.target.parentElement.style.border = '1px solid rgb(199, 199, 199)'
            e.target.parentNode.firstElementChild.style.color = 'rgb(199, 199, 199)'
        })

        $('#image_container').hover(e => {
            $('#change_div').show().css('display', 'flex')
        }, e => {
            $('#change_div').hide()
        })

        $('#change_div').click(e => {
            document.getElementById('id_profile_pic').click()
        })

        function changeBackgroundImage(img) {
            $("#main_content > p").css('display', 'block')
        }
        
    </script>
</body>
</html>

src/templates/ProfilePage/tweet.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    <link rel="stylesheet" href="{% static 'ProfilePage/css/tweet_style.css' %}">
    <title>{{tweet.user.username}}</title>
</head>
<body>
    <!-- <h1>Sent by: <a href="/{{tweet.user.username}}">{{tweet.user.username}} #{{tweet.user.userTag}}</a></h1>
    <h3 style="display: inline;">Tweet: </h3>
    <p style="display: inline; color: rgb(154, 154, 154);">{{created_on}}</p>
    <p>{{tweet.message}}</p> -->

    <div class="container">
        <div class="header_container">
            <div id="logo_container">
                <img src="{% static 'LoginPage/img/twitter_small_logo.png'%}" alt="" onclick="window.location.href = '/home/'">
                <a href="/home/"><p>Twooter</p></a>
            </div>
            <div id="profile_tab">
                <a href="/{{user.user.username}}" id="profile_tab_button">
                    <p>{{  user.user.username }}</p> 
                    <img src="/media/{{user.profile_pic}}" alt="Profile Pic">
                </a>
            </div>
        </div>
        <div id="main_container">
            <div id="nav_container">
                <div id="nav_buttons">
                    <a href="/home/" class="nav_button">
                        <span class="material-symbols-outlined">
                            home
                        </span>
                        <p>Feed</p>
                    </a>
                    <a href="/{{user.user.username}}/" class="nav_button">
                        <span class="material-symbols-outlined">
                            person
                        </span>
                        <p>Profile</p>
                    </a>
                </div>
                <div id="logOut_container">
                    <button onclick="logOut()">Log Out</button>
                </div>
            </div>
            <div id="tweets-container">
                <div id="tweets_box">
                    <div class="tweet">
                        <a href="/{{tweet.user.username}}">
                        <img src="/media/{{profile_pic}}" alt="Profile Pic">
                        <p class="author">@{{tweet.user.username}}</p>
                        <p style="display: inline; color: gray;">{{created_on}}</p>
                        </a>
                        <p class="message">{{tweet.message}}</p>
                    </div>
                </div>
            </div>
            <div id="activity_container"></div>
        </div>
    </div>

</body>
</html>